project:
  type: website
  output-dir: docs

website:
  title: "DSFI_A2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Appendix.qmd
      - ChatGPT.qmd
      - work_split.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true