---
title: "DSFI_A2"
---

# Introduction

The State of the Nation Address (SONA) serves as an annual narrative roadmap of South Africa, highlighting its triumphs, challenges, and future trajectories. Delivered by the President, this address not only provides a summary of the nation's current status but also sets the tone for governmental strategies, policies, and priorities for the coming year. The addresses serve as a snapshot into South Africa's challenges, successes and socioeconomic state at a given time. Hence analysis of the sentiment and topics of the speeches can provide a framework for a deeper understanding of trends and topics from presidents' rhetoric less clouded by the bias of political analysts. 

In the era of data science, where Natural Language Processing(NLP) has become a potent tool to extract meaningful patterns from large volumes of textual data, it is of profound interest to apply such methods to SONA speeches. By employing advanced techniques such as sentiment analysis and topic modelling, one can unearth the latent themes dominating these addresses over three decades and gauge the sentiment fluctuations accompanying them. This presents a data-driven perspective on South Africa's political discourse,

The following proceeds follow this course. Firstly a literature review will be conducted on the existing sentiment analysis and topic modelling methods available and used in academia and industry. Thereafter a preliminary exploration of the data occurs to understand the structure and potential trends in the data prior to modelling applications. The Methods section will then detail the sentiment analysis, topic modelling and metrics used in these models. The results of the paper are briefly presented and interpreted before we discuss the overall trends and findings of the paper. We conclude by surmising the findings of the paper, highlighting limitations and presenting avenues for future research into SONA NLP work. 


# Literature Review

## Sentiment Analysis

Sentiment Analysis is a prominent field within the broader scope of NLP techniques, and it has gained significant attention in scientific research in recent years. Sentiment classification, specifically polarity estimation, is amongst the most extensively studied tasks of sentiment analysis. Polarity is often categorized as either positive or negative (Wang et al., 2014). This is what our sentiment analysis will focus on. 

According to the wider literature, there are two primary approaches to sentiment analysis, the machine learning and lexicon-based approaches. The other primary approach to sentiment analysis is the lexicon-based approach. This approach analyzes each word in a document and gives it a score, on a scale where one side is completely negative, and the other is completely positive, with neutral in the middle. For example, words that would get a negative rating include, “ugly”,  while a positively rated word is “good”(Ligthart et al., 2021). (Vinodhini 2012) notes that lexicons are heavily reliant on the domain, due to the type of language used in different fields. This is why adjusting the lexicon to the target domain is needed, however can be very time consuming.

Popular lexicons include the AFINN lexicon, which gives words a rating between -5 and 5, with -5 meaning a very negative word while 5 indicates that the word is very positive (Al-Shabi, 2020), and  the NRC Emotion Lexicon (Mohammad & Turney, 2010) which focuses on emotional words only. This provides a list of words that are classified as “negative”, “positive”, and then based on (Plutchik, 1980), words are given corresponding emotions, such as: “anger”, “disgust”, “joy”, etc. These are the two lexicons we will be using in this paper.

Machine learning approaches for sentiment analysis tasks are often divided into three categories: unsupervised learning, semi-supervised learning, and supervised learning. Unsupervised learning methods cluster unlabeled data into groups that exhibit similarity (Li and Liu 2014). Semi-supervised learning makes use of both labeled and unlabelled data in the training process (da Silva et al. 2016a, b),  while supervised learning, which is the most human-intensive, occurs when a model is trained on fully labeled data. This can often result in the optimal model performance, however due to the requirement of labeled data it can be inefficient to acquire (Hemmatian and Sohrabi 2017).

(Yadav and Vishwakarma, 2019) reviewed over 100 papers which used deep learning (subset of machine learning) techniques to perform sentiment analysis, and found that the most common deep learning models are RNNs, CNNs, and LSTMs, with the latter providing the best performance. They also said that utilizing machine learning approaches to conduct sentiment analysis was a promising field, while noting that the dataset needs to be large enough for a respectable analysis to take place, which can be a challenge.

Furthermore, (Loureiro et al., 2022) showed the importance of Time language models, which are a set of language models which undergo continual learning on, in this case, tweets. (Loureiro et al., 2022) shows that this approach enhances the models ability to deal with out-of-distribution inputs, as well enhances competitiveness with standard benchmark tests. They’re also seen to deal well with the problem of concept drift. Since our data is over a long period of time, we will be using these time language models too.

## Topic Modelling

In the 1980s, topic modelling emerged as a means to enhance the accuracy of information retrieval systems. (Deerwester et al., 1990) founded one of the earliest topic models known as Latent Semantic Analysis (LSA). LSA groups documents based on latent semantic formations, and makes the assumption that words with similar semantic meanings tend to co-occur. This found great use in document retrieval systems because users were no longer required to employ the exact words found in the desired documents - similarity could be determined through a broader semantic context.

Blei et al. (2003) advanced the techniques implemented in LSA by developing a related modelling algorithm called Latent Dirichlet Allocation (LDA). In LDA, a document is seen as a collection of words drawn from unobserved topics. LDA subsequently assesses the likelihood distribution of a specific word across a range of topics and then the distribution of a specific topic across a collection of documents.

```{python}
#| include: false
pip install nrclex
```
```{python}
#| include: false

pip install tabulate
```
```{python}
#| include: false
pip install transformers
```

```{python}
#| include: false
pip install pyLDAvis
```

```{python}
#| include: false
 pip install afinn
```

```{python}
#| include: false
# General imports
import pickle
from joblib import dump, load
import os
import pandas as pd
import re
import numpy as np
import string

# NLTK imports
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

# Visualization imports
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud, STOPWORDS

# Preprocessing imports
from sklearn.feature_extraction.text import CountVectorizer, ENGLISH_STOP_WORDS, TfidfVectorizer
from sklearn.preprocessing import LabelEncoder

# Model selection imports
from sklearn.model_selection import train_test_split, GridSearchCV

# Machine learning model imports
from sklearn.svm import SVC
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.regularizers import l2
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from catboost import Pool, cv, CatBoostClassifier

# Word embedding imports
from gensim.models import Word2Vec

# LDA model imports
from gensim.models import LdaModel
from gensim import corpora
import pyLDAvis.gensim_models as gensimvis
import pyLDAvis

# Metrics import
from sklearn.metrics import classification_report, accuracy_score
```


```{python}
#| echo: false
#| eval: false
#| include: false
folder_path = 'speeches'  
files = os.listdir(folder_path)
files = sorted([file for file in files if os.path.isfile(os.path.join(folder_path, file)) and file.endswith('.txt')])

president_names = []

pattern = r'_(.+?)\.txt'  
for file in files:
    match = re.search(pattern, file)
    if match:
        president_name = match.group(1)
        # Remove the "_2" suffix from the president names here
        cleaned_president_name = president_name.replace('_2', '')
        president_names.append(cleaned_president_name)
    else:
        print(f"Warning: No match found in filename: {file}")
        president_names.append('Unknown')  # Placeholder for missing names

# Check  lengths
if len(files) != len(president_names):
    print(f"Warning: Number of files ({len(files)}) does not match number of president names ({len(president_names)})")

def preprocess_speeches(speech):
    # Tokenize the text
    tokens = word_tokenize(speech)
    # Remove punctuation and convert to lowercase
    tokens = [token.lower() for token in tokens if token not in string.punctuation]
    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [token for token in tokens if token not in stop_words]
    # Lemmatize tokens
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(token) for token in tokens]
    for i in range(len(tokens)):
        clean_token = ''.join(char for char in tokens[i] if char.isalpha())
        tokens[i] = clean_token
    tokens = [token for token in tokens if len(token)>2]
    return tokens


df = pd.DataFrame(columns=['Presidents', 'Sentences'])
tokenised_speeches = pd.DataFrame(columns=['Presidents', 'Tokens'])  # To store the speeches tokenized by word

# Iterate over all files and extract sentence
for file_index in range(len(files)):
    file_path = os.path.join(folder_path, files[file_index])
    with open(file_path, 'r', encoding='utf-8') as file:
        speech = file.read()    
        tokens = preprocess_speeches(speech)

        lines = file.readlines()[2:] 

    text = ' '.join(lines)
    sentences = sent_tokenize(text)
    cleaned_sentences = [sentence.replace('\n', '') for sentence in sentences]

    current_president = president_names[file_index]
    dftemp = pd.DataFrame({'Presidents': [current_president] * len(cleaned_sentences), 'Sentences': cleaned_sentences})
    dftemp2 = pd.DataFrame({'Presidents': [current_president] * len(tokens), 'Tokens': tokens})
    df = pd.concat([df, dftemp], axis=0, ignore_index=True)
    tokenised_speeches = pd.concat([tokenised_speeches, dftemp2], axis=0, ignore_index=True)

df.reset_index(drop=True, inplace=True)
tokenised_speeches.reset_index(drop=True, inplace=True)
tokenised_speeches = tokenised_speeches[~tokenised_speeches['Tokens'].str.contains(r'[0-9]', na=False)]  ## Remove numeric tokens


# Save the DataFrame to a CSV file
#df.to_csv('finalSentences2.csv', index=False)
#tokenised_speeches.to_csv('finalTokens.csv', index=False)

```


```{python}
#| include: false
a2data = pd.read_csv("finalSentences2.csv")
a2tokens = pd.read_csv("finalTokens.csv")
```


# Methods
## Sentiment Analysis

### AFINN

The AFINN lexicon is a valuable resource consisting of a vast list of English words, with each word meticulously assigned a sentiment score. These scores span a numerical range from -5 to 5, encompassing the spectrum of sentiments present in the English language. Negative sentiment is represented by scores in the negative range, where more negative scores signify a greater intensity of negative emotion associated with the word. Conversely, positive sentiment is conveyed through positive scores, with the magnitude of the positive number indicating the degree of positivity linked to the word. Words with a neutral sentiment receive a score of 0, indicating their emotional neutrality.

In practice, the sentiment analysis process unfolds by systematically evaluating the words within each sentence in the dataset. For each word in a sentence, its associated sentiment score is extracted from the AFINN lexicon. Subsequently, the sentiment scores for all the words in a sentence are summed to compute the overall sentiment of that sentence. This method, in turn, facilitates the categorization of sentences by the president delivering them. The collective sentiment analysis allows for a comprehensive examination of the language employed and the emotional disposition of each president, thereby providing valuable insights into the emotional nuances that characterize their speeches.

### NRC lexicon

The NRC lexicon is a comprehensive linguistic resource that encompasses a substantial collection of English words. Each word in this lexicon is associated with specific emotional and sentiment categories, such as joy, sadness, anger, trust, and fear, among others. These categories offer a more detailed perspective on the emotions of South African presidents compared to other lexicons. Words are tagged with binary values indicating whether they evoke a particular emotion or sentiment, making it possible to identify not only the polarity of the sentiment (positive or negative) but also the specific emotional dimension.

This is conducted by once again analysing each sentence in the dataset and selecting the emotion associated with each word within a sentence based on the NRC lexicon. By assigning these emotional labels to individual words, a more comprehensive and fine-grained understanding of sentiment and emotion within text is achieved. The collective emotional and sentiment labels for words in a sentence are then aggregated over all sentences to compute the overall sentiment and emotional composition of each president. This grouping by president allows for an in-depth exploration of the specific emotional and sentimental patterns and variations exhibited by each president in their speeches. This approach thus offers the positivity/negativity metric offered by the AFINN lexicon, but also decomposes these broad categories into specific emotions.

### RoBERTa Transfer Learning

For sentiment analysis, we also employed a model belonging to hugging face called "twitter-roberta-base-sentiment-latest" and "". The architecture for these models is largely the same, but "" differs in that it was trained primarily on political tweets, which is lesser in the training data size but potentially more domain relevant to the task at hand. 

 This is a transformer-based transfer learning approach. Essentially this means that the model has been pretrained on data to learn how to assign sentiment scores then the trained model is used to extract sentiment scores for our dataset. The model used is more specifically considered a time language model. The time Language Models (LM) foundation is anchored on the RoBERTa architecture, which is a refined variant of BERT (Bidirectional Encoder Representations from Transformers). One of the standout characteristics of RoBERTa is its bidirectional context processing. Unlike conventional models, RoBERTa reviews words in relation to their entire surrounding context, absorbing nuances from both the preceding and following parts of the text. 

Moreover, RoBERTa adopts a Transformer architecture, known for its self-attention mechanism. This mechanism empowers RoBERTa to assign varying importance levels to distinct words in a sentence, ensuring it recognizes and processes dependencies irrespective of their dispersion within the body of text.

Key to its training process is  RoBERTa's utilization of masked language modelling. Here, select words in a sentence are intermittently substituted with a [MASK] token. The model is then tasked with deducing the original word, relying solely on the surrounding context. This method is important in refining RoBERTa's grasp of language semantics.

Differentiating from its predecessor, BERT, RoBERTa's pretraining process has been further optimized. It undergoes training on a more expansive dataset of 10 years of Twitter data. Another differentiating factor from BERT is how RoBERTa dispenses with the next sentence prediction task, a staple in BERT, and recalibrates the masking strategy to elevate its efficiency. The RoBERTa model for a given body of text returns a class probability value of -1 for negative sentiment, 0 for neutral and 1 for positive the highest probability over the three classes is the assigned sentiment. We multiply the class values by their probabilities and sum them to gain a sentiment score between -1 and 1 and use this coupled with the assigned sentiment class for our model evaluation. 



## Topic Modelling 
### Latent Dirichlet Allocation

Latent Dirichlet Allocation (LDA) is a probabilitistic model which was implemented as a topic modelling technique to extract meaningful latent topics from the SONA corpus. The SONA speeches are pre-processed to remove stop words, punctuation, and other textual debris. The documents are then lemmatised and tokenised into word-tokens. These tokens are used to create a document-term matrix that contains the frequency of words in each document. The Gensim library was used to enable the training of LDA models on the preprocessed data, and facilitated the extraction of topics associated with their respective word distributions. The resulting topics were then visualized using the pyLDAvis package, to create a interpretable overview of the extracted topics. This process was first performed using a corpus containing all thirty-six speeches. The initial model had five topics, and the number of topics was iteratively decreased until the topics differentiated nicely across the latent variables. This number of topics (3) was then used to train a model for each president's individual corpus of speeches. 

### Probablistic Latent Semantic Analysis

Probablistic Latent Semantic Analysis (pLSA) is the second topic modelling technique used to extract latent topics from the corpus of documents. The text data is preprocessed similarly to LDA; removing stop words, punctuation, and debris, followed by lemmatisation and tokenisation, and then the creation of a document-term matrix. After the pre-processing is complete, pLSA begins by initialising random probabilities for topics and words within topics. The topic and word probabilties are then iteratively updated using the Expectation Maximisation (EM) algorithm. Once the algorithm reaches convergence, there is a resulting set of topics, each containing a set of words. The Gensim package was used to implement the training of the pLSA models, and the matplotlib package was used to visualise the results.

```{python}
#| include: false
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoConfig
import numpy as np
from scipy.special import softmax
```

# Results

## Data Exploration 

In analyzing the word clouds of various South African presidents in Figure X, there's a discernible emphasis on governance, nation-building, and the welfare of the South African people. Motlanthe and Mbeki highlighted governmental programs and assured development, while Mandela accentuated societal unity and nation-building. Ramaphosa's emphasis leaned towards economic investment and support, Zuma prioritized governmental initiatives and societal support, and deKlerk focused on constitutional and governance reforms. Across all presidents, the persistent themes underscore a dedication to governance, the progress of South Africa, and the betterment of its citizens.

```{python}
#| echo: false
#| fig-cap: "Figure X: Wordcloud per president"
data = a2data
def remove_stopwords(sentence):
    words = sentence.split()
    cleaned_words = [word for word in words if word.lower() not in STOPWORDS]
    return ' '.join(cleaned_words)

# Apply the function to remove stop words from each sentence in the DataFrame
data['Cleaned_Sentences'] = data['Sentences'].apply(remove_stopwords)

# Group the cleaned sentences by president
grouped = data.groupby('Presidents')['Cleaned_Sentences'].apply(' '.join).reset_index()

# Initialize a dictionary to store word clouds for each president
wordclouds = {}

# Generate a word cloud for each president
for index, row in grouped.iterrows():
    wordcloud = WordCloud(width=800, height=400, background_color='white').generate(row['Cleaned_Sentences'])
    wordclouds[row['Presidents']] = wordcloud

# Display the word clouds
plt.figure(figsize=(15, 10))
for i, (president, wordcloud) in enumerate(wordclouds.items(), 1):
    plt.subplot(3, 2, i)  
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.title(president)
    plt.axis("off")
plt.show()
```



## AFINN lexicon

```{python}
#| echo: false
#| eval: true
#| include: false


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
from sklearn.preprocessing import StandardScaler
from afinn import Afinn
 
#instantiate afinn
afn = Afinn()
data = pd.read_csv("finalSentences2.csv")

# compute scores (polarity) and labels
scores = [afn.score(sentence) for sentence in data["Sentences"]]
sentiment = ['positive' if score > 0
						else 'negative' if score < 0
							else 'neutral'
								for score in scores]
	
# dataframe creation
afn_df = pd.DataFrame()
afn_df['Presidents'] = data['Presidents']
afn_df['Sentences'] = data['Sentences']
afn_df['scores'] = scores
afn_df['sentiments'] = sentiment

# scaler = StandardScaler()
# scaled_data = scaler.fit_transform(afn_df['scores'].values.reshape(-1,1))
# afn_df['scores'] = scaled_data.squeeze()

presidents_order = ['Mandela', 'deKlerk', 'Mbeki', ' Motlanthe', 'Zuma', 'Ramaphosa']
mean_scores_per_president = afn_df.groupby('Presidents')['scores'].mean()
adjusted_presidents_order = ['deKlerk'] + [president for president in presidents_order if president != 'deKlerk']
mean_scores_reordered = mean_scores_per_president.reindex(adjusted_presidents_order)

# save object
# mean_scores_reordered.to_csv('wes_appendix/mean_scores_reordered.csv')
```

The mean sentiment scores per president show President Mbeki exhibiting the highest mean sentiment score at approximately 1.65, suggesting a generally positive sentiment in his speeches. President Motlanthe followed closely with a mean sentiment score of approximately 1.44, indicating a similar trend of positively oriented speeches. In contrast, President de Klerk presented the lowest mean sentiment score, around 0.67, while Presidents Ramaphosa and Zuma demonstrated mean sentiment scores around 0.95 and 0.92, respectively.


```{python}
#| echo: False
mean_scores_reordered = pd.read_csv('wes_appendix/mean_scores_reordered.csv')
# Plotting the reordered mean sentiment scores
plt.figure()
#mean_scores_reordered.plot(kind='bar', color='skyblue')
plt.bar(mean_scores_reordered['Presidents'], mean_scores_reordered['scores'], color='skyblue')

plt.title('Mean Sentiment Scores per President')
plt.xlabel('President')
plt.axhline(0, color='red', linestyle='--')  #line at y=0 for reference
plt.ylabel('Mean Sentiment Score')
plt.xticks(rotation=90)
#plt.yticks(fontsize=16)  # Set the font size for y-axis tick labels
plt.tight_layout()
plt.show()
```

```{python}
#| echo: false
#| include: false
colors = {'negative': '#FF9999', 'neutral': '#99CCFF', 'positive': '#99FF99'}
sentiment_counts = afn_df.groupby('Presidents')['sentiments'].value_counts(normalize=True).unstack().fillna(0)
```


Figure X below shows that deKlerk is once again seen to possess less positive sentiments in his speeches than most of the other presidents, apart from Zuma, who has a very similar amount of positivity. Motlanthe and Mbeki are seen to have the greatest proportion of positive sentiments, while Zuma is seen to have the largest amount of neutral sentiments compared to the other presidents. As well as having the smallest proportion of positivity, deKlerk also has a large proportion of his sentences carrying negative sentiments.

```{python}
# save object
# sentiment_counts.reindex(adjusted_presidents_order).to_csv('wes_appendix/sentiment_counts.csv')
sentiment_counts = pd.read_csv("wes_appendix/sentiment_counts.csv")
sentiment_counts.plot(kind='bar', stacked=True, color=[colors[col] for col in sentiment_counts.columns if col != 'Presidents'])
plt.title('Sentiment Distribution per President')
plt.ylabel('Percentage')
plt.xlabel('President')
plt.legend(title='Sentiment')#, fontsize=20, title_fontsize=20)
plt.tight_layout()
plt.xticks(rotation=0)
#plt.yticks(fontsize=16) 
plt.show()
```


Figure Ax in the appendix shows the sentiments of each president over time. However, once again the extreme granularity of the plots makes it difficult to extract any useful information. Noticeably however, deKlerk's strong negative sentiments are apparent from such a broad scoped view.

The histograms below show the sentiment score distribution for the presidents. All histograms appear to be slightly skewed to the left, indicating a high frequency of positive sentiment. Mandela appears to have the most evenly spread sentiment distribution, with the fewest number of protruding bars, while de Klerk mainly has a uniform sentiment distribution, with a notable deviation from that occuring in the neutral sentiment territory. Ramaphosa's, Mbeki's and Zuma's sentiment distributions are both centered on the positive side of zero, indicating a generally positive sentiment, while Motlanthe's most common sentiment is actually slightly negative, however that is offset by the high frequency of positive sentiments.

```{python}
#| echo: false
#| eval: true

pastel_colors = ['#FFB3BA', '#FFDFBA', '#FFFFBA', '#BAFFC9', '#BAE1FF', '#D9BAFF']

def plot_histogram(president, color, ax):
    """Plot histogram of sentiment scores for a given president on a given axes."""
    president_df = afn_df[afn_df['Presidents'] == president]
    
    x_range = max(president_df['scores']) - min(president_df['scores'])
    half_x_range = x_range / 2
    
    # Set the x-axis limits to center the histogram around 0
    ax.set_xlim(-10, 10)

    ax.hist(president_df['scores'], bins=30, color=color, edgecolor='white')
    ax.set_title(f'{president}')
    ax.set_xlabel('Sentiment Score')
    ax.set_ylabel('Frequency')
    ax.tick_params(axis='x')
    ax.tick_params(axis='y')
    ax.grid(axis='y', linestyle='--', linewidth=0.5)

# Creating a 2x3 grid plot for histograms of all presidents
fig, axes = plt.subplots(2, 3)
fig.suptitle('Distribution of Sentiment Scores for each President')

for president, color, ax in zip(adjusted_presidents_order, pastel_colors, axes.ravel()):
    plot_histogram(president, color, ax)

# Adjust layout
plt.tight_layout()
plt.subplots_adjust(top=0.90)
plt.show()

```



## NRC

```{python}
#| echo: false
#| eval: true
#| include: false
import pandas as pd
from nrclex import NRCLex

# Function to find the top emotions for a text
def find_top_emotions(text):
    emotion = NRCLex(text)
    return emotion.top_emotions

# Apply the function to each row in the DataFrame
data['Top_Emotions'] = data['Sentences'].apply(find_top_emotions)

unique_emotion_columns = ['fear', 'anger', 'anticipation','anticip', 'trust', 'surprise', 'positive', 'negative', 'sadness', 'disgust', 'joy']
presidents = data['Presidents'].unique()

president_dataframes = {president: pd.DataFrame(0, columns=unique_emotion_columns, index=[0]) for president in presidents}

for index, row in data.iterrows():
    president = row['Presidents']
    emotions = dict(row['Top_Emotions'])
    #president_df = president_dataframes[president]
    
    # Iterate through unique_emotion_columns
    for emotion_column in emotions.keys():
        if emotion_column in emotions:
            value = emotions[emotion_column]
            president_dataframes[president][emotion_column] += value

president_dataframes['Mandela']

for pres in presidents:
    president_dataframes[pres] = president_dataframes[pres].div(president_dataframes[pres].sum(axis=1), axis=0)

for president, df in president_dataframes.items():
    if 'anticipation' in df.columns and 'anticip' in df.columns:
        df['anticipation'] += df['anticip']  # Add 'anticip' to 'anticipation'
        df.drop(columns=['anticip'], inplace=True)  # Remove 'anticip' column

pastel_colors = ['#FFB3BA', '#FFDFBA', '#FFFFBA', '#BAFFC9', '#BAE1FF', '#D9BAFF']
fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle('Distribution of Sentiment Scores for each President', fontsize=20)

order = ['deKlerk','Mandela', 'Mbeki', ' Motlanthe', 'Zuma', 'Ramaphosa']

for president, ax, colour in zip(order, axes.ravel(), pastel_colors):
    data = president_dataframes[president]
    x = list(data.keys())
    x.remove('positive')
    x.remove('negative')
    y = data[x].values.squeeze()
    ax.set_ylim(0, 0.25)
    ax.bar(x, y, color=colour)
    ax.set_title(president)
    # ax.set_xlabel('Sentiment Category', fontsize=16)
    ax.set_ylabel('Sentiment Score', fontsize=16)
    ax.tick_params(axis='x')#, labelsize=16)
    ax.tick_params(axis='y', labelsize=16)

# Adjust layout
#plt.tight_layout()
plt.subplots_adjust(top=0.90)
plt.show()
```

Using the NRC emotion lexicon we see that all presidents have their most common sentiment being positive, while the particular emotions in there sentences differ. A common emotion amongst all presidents is trust. Anticipation is a frequently evoked emotion from the presidents, besides for deKlerk. Other relatively common emotions include fear and joy.

## RoBERTa 

```{python}
#| echo: false
#| eval: false
#| include: false
data = a2data

import numpy as np
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoConfig

# Assuming a2data is loaded
data = a2data

# Define the preprocess function
def preprocess(text):
    new_text = []
    for t in text.split(" "):
        t = '@user' if t.startswith('@') and len(t) > 1 else t
        t = 'http' if t.startswith('http') else t
        new_text.append(t)
    return " ".join(new_text)

# Define the model details
MODEL = "cardiffnlp/twitter-roberta-base-sentiment-latest"
tokenizer = AutoTokenizer.from_pretrained(MODEL)
config = AutoConfig.from_pretrained(MODEL)
model = AutoModelForSequenceClassification.from_pretrained(MODEL)

# Preprocess the sentences
data['Preprocessed_Sentences'] = data['Sentences'].apply(preprocess)

# Compute the weighted sentiment score and get the model's sentiment classification
def compute_sentiment_data(text):
    # Tokenize and get model output
    encoded_input = tokenizer(text, return_tensors='pt', truncation=True, max_length=512)
    output = model(**encoded_input)
    scores = output[0][0].detach().numpy()
    probabilities = softmax(scores)
    
    # Compute the weighted sentiment score
    sentiment_values = np.array([-1, 0, 1])  # Corresponding to Negative, Neutral, and Positive
    sentiment_score = np.dot(sentiment_values, probabilities)
    
    # Get the model's sentiment classification
    ranking = np.argsort(scores)
    ranking = ranking[::-1]
    label = config.id2label[ranking[0]]
    
    return sentiment_score, label

# Predict sentiment data for the preprocessed sentences
sentiment_data = data['Preprocessed_Sentences'].apply(compute_sentiment_data)
data['Sentiment_Score'] = [s[0] for s in sentiment_data]
data['Predicted_Label'] = [s[1] for s in sentiment_data]

# Save the results
data.to_csv("HFM1_SentimentData.csv")
```

Figure XXX plots the mean sentiment score(-1 to 1, where -1 is perfectly negative, 0 is neutral and 1 is positive) across all presidents where presidents have been ordered by time. Beginning with de Klerk, there is a noticeable negative sentiment. However, as we transition to Mandela's era, a significant shift occurs, with sentiment becoming predominantly positive. This positive trend not only continues but also amplifies during Mbeki's tenure. 

Following Mbeki, Motlanthe's sentiment score experiences a slight dip but remains firmly in the positive territory, suggesting his rhetoric, likely inifluenced by the poor economic conditions during this temulruous time in south africas politcs, was less positive than Mbeki's. The highest peak in positive sentiment is observed during Zuma's term, which is interesting considering the slide of economic performance during his tenure().This may point to a juxtoposition in his presentation of the stte of the nation and the reality of the peroid both regarding corruption and economic stability() However, it's noteworthy that Ramaphosa's sentiment, while still being robustly positive, sees a decline from the high set by Zuma, potentially indicating the effects of rhetoric regarding the COVID-19 pandemic.


```{python}
#| echo: false
#| fig-cap: "Figure X: RoBERTa 1 Mean Sentiment Scores per President"
HFM1 = pd.read_csv("HFM1_SentimentData.csv")
presidents_order = ['Mandela', 'deKlerk', 'Mbeki', ' Motlanthe', 'Zuma', 'Ramaphosa']
mean_scores_per_president = HFM1.groupby('Presidents')['Sentiment_Score'].mean()
adjusted_presidents_order = ['deKlerk'] + [president for president in presidents_order if president != 'deKlerk']
mean_scores_reordered = mean_scores_per_president.reindex(adjusted_presidents_order)

# Plotting the reordered mean sentiment scores
#plt.figure(figsize=(12, 7))
mean_scores_reordered.plot(kind='bar', color='skyblue')
plt.xlabel('President')
plt.ylabel('Mean Sentiment Score')
plt.axhline(0, color='red', linestyle='--')  #line at y=0 for reference
plt.tight_layout()
plt.show()
```

In Figure XXX we plot the proportion of each sentiment class across all sentences per president.Mandela and Ramaphosa primarily have positive and neutral sentiments, with Mandela possessing a slightly broader share of positive mentions. De Klerk presents an interesting case; while he has the least proportion of positive sentiments among all the presidents, he also claims the highest negative sentiment. Mbeki and Zuma display an almost balanced distribution between positive and neutral sentiments, with Mbeki tipping slightly more towards the positive end. Motlanthe distinctly stands out, characterized by an overwhelming positive sentiment that far surpasses both the neutral and negative sentiments.

```{python}
#| echo: false
#| fig-cap: "Figure X: RoBERTa 1 Sentiment Distribution per President "
colors = {'negative': '#FF9999', 'neutral': '#99CCFF', 'positive': '#99FF99'}
sentiment_counts = HFM1.groupby('Presidents')['Predicted_Label'].value_counts(normalize=True).unstack().fillna(0)

sentiment_counts.reindex(adjusted_presidents_order).plot(kind='bar', stacked=True, color=[colors[col] for col in sentiment_counts.columns])
plt.ylabel('Percentage')
plt.xlabel('President')
plt.legend(title='Sentiment')
plt.tight_layout()
plt.show()
```

To gain a depper understading of the change in sentiment over timie for each given president, and their speeches, we can look to figure XXX in the appendix. While the plot dos provide a granular insight into the variety of sentiment across sentences in presidents' speaches the lack of discernable trend makes the plot difficult to interpret. Furthermore the sentiment aggregatioin plots at an overall president level provides sufficient insiight.  Figure XXX plots the distribution of sentiment scores for each president. For de Klerk, there's a noticeable tilt towards neutral to negative sentiments. On the other hand, Mandela's mentions are predominantly positive. Mbeki's sentiment profile reveals an overwhelmingly positive tone, with more neutrality in tone than Mandela. Motlanthe's mentions also predominantly exhibit positivity, especially between the 0.50 to 1.00 range. Zuma presents a diverse sentiment spectrum; while there's a substantial representation in the positive range, especially towards the higher end, there's also a notable amount neutral sentiment and almost no negative rhetoric. Lastly, discussions about Ramaphosa are mostly tinted with positivity, particularly around the 0.50 to 0.75 range, although some neutral and negative sentiments are present. Overall, while Mandela, Mbeki, Motlanthe, Zuma, and Ramaphosa's mentions lean more towards positivity, de Klerk's profile hints at a more neutral with a  greater tilt towards negativity. 

```{python}
#| fig-cap: "Figure X: RoBERTa 1 Distribution of Sentiment Scores for each President"
#| echo: false
pastel_colors = ['#FFB3BA', '#FFDFBA', '#FFFFBA', '#BAFFC9', '#BAE1FF', '#D9BAFF']

def plot_histogram(president, color, ax):
    """Plot histogram of sentiment scores for a given president on a given axes."""
    president_df = HFM1[HFM1['Presidents'] == president]
    ax.hist(president_df['Sentiment_Score'], bins=30, color=color, edgecolor='white')
    ax.set_title(f'{president}')
    ax.set_xlabel('Sentiment Score')
    ax.set_ylabel('Frequency')
    ax.grid(axis='y', linestyle='--', linewidth=0.5)

# Creating a 2x3 grid plot for histograms of all presidents
fig, axes = plt.subplots(2, 3)

for president, color, ax in zip(adjusted_presidents_order, pastel_colors, axes.ravel()):
    plot_histogram(president, color, ax)

# Adjust layout
plt.tight_layout()
plt.subplots_adjust(top=0.90)
plt.show()
```

## RoBERTa: Domain Specific

```{python}
#| eval: false
#| include: false
# Assuming a2data is loaded
data = a2data

# Define the preprocess function
def preprocess(text):
    new_text = []
    for t in text.split(" "):
        t = '@user' if t.startswith('@') and len(t) > 1 else t
        t = 'http' if t.startswith('http') else t
        new_text.append(t)
    return " ".join(new_text)

# Define the model details
MODEL = "cardiffnlp/xlm-twitter-politics-sentiment"
tokenizer = AutoTokenizer.from_pretrained(MODEL)
config = AutoConfig.from_pretrained(MODEL)
model = AutoModelForSequenceClassification.from_pretrained(MODEL)

# Preprocess the sentences
data['Preprocessed_Sentences'] = data['Sentences'].apply(preprocess)

# Compute the weighted sentiment score and get the model's sentiment classification
def compute_sentiment_data(text):
    # Tokenize and get model output
    encoded_input = tokenizer(text, return_tensors='pt', truncation=True, max_length=512)
    output = model(**encoded_input)
    scores = output[0][0].detach().numpy()
    probabilities = softmax(scores)
    
    # Compute the weighted sentiment score
    sentiment_values = np.array([-1, 0, 1])  # Corresponding to Negative, Neutral, and Positive
    sentiment_score = np.dot(sentiment_values, probabilities)
    
    # Get the model's sentiment classification
    ranking = np.argsort(scores)
    ranking = ranking[::-1]
    label = config.id2label[ranking[0]]
    
    return sentiment_score, label

# Predict sentiment data for the preprocessed sentences
sentiment_data = data['Preprocessed_Sentences'].apply(compute_sentiment_data)
data['Sentiment_Score'] = [s[0] for s in sentiment_data]
data['Predicted_Label'] = [s[1] for s in sentiment_data]

# Save the results
data.to_csv("HFM2_SentimentData.csv")

data.head()
```

In Figure XXX we look at the mean sentiment scorees for each president. The resuls are largely similar as the prior model. De Klerk remains the president with the lowest mean sentiment score while Zuma retainis the highest value. The other preseidents scores while slighly altered still behave similar relative to eachother.

```{python}
#| echo: false
#| fig-cap: "Figure X: RoBERTa 2 Mean Sentiment Scores per President "
HFM2 = pd.read_csv("HFM2_SentimentData.csv")
presidents_order = ['Mandela', 'deKlerk', 'Mbeki', ' Motlanthe', 'Zuma', 'Ramaphosa']
mean_scores_per_president = HFM2.groupby('Presidents')['Sentiment_Score'].mean()
adjusted_presidents_order = ['deKlerk'] + [president for president in presidents_order if president != 'deKlerk']
mean_scores_reordered = mean_scores_per_president.reindex(adjusted_presidents_order)

# Plotting the reordered mean sentiment scores
#plt.figure(figsize=(12, 7))
mean_scores_reordered.plot(kind='bar', color='skyblue')
plt.xlabel('President')
plt.ylabel('Mean Sentiment Score')
plt.axhline(0, color='red', linestyle='--')  #line at y=0 for reference
plt.tight_layout()
plt.show()
```


Now looking to the proportion of sentiment classes per president in Figure XXX. We note that de Klerk's mean sentiment score became more positve we find that the proportioin of negative sentences has remained largely the same rather neutral sentencees in the previous model have now been classified as positve. While the results do look similar there is a clear trend of lesser neutral sentences, possibly speaking to the more domaini specific model's ability to better discern sentiment of political rhetoric. 

```{python}
#| echo: false
#| fig-cap: "Figure X: RoBERTa 2 Sentiment Distribution per President"
colors = {'Negative': '#FF9999', 'Neutral': '#99CCFF', 'Positive': '#99FF99'}
sentiment_counts = HFM2.groupby('Presidents')['Predicted_Label'].value_counts(normalize=True).unstack().fillna(0)

sentiment_counts.reindex(adjusted_presidents_order).plot(kind='bar', stacked=True, color=[colors[col] for col in sentiment_counts.columns])
plt.ylabel('Percentage')
plt.xlabel('President')
plt.legend(title='Sentiment')
plt.tight_layout()
plt.show()
```


Looking to the distribution of sentiments by presidents in figure XXX. De Klerk's sentiment heavily leans towards the negative, with only a sparse presence of positive sentiment. Contrastingly, Mandela garners a majority of positive sentiments, although there's a consistent representation across all sentiment spectrums, indicating diverse opinions. Mbeki's sentiment profile is unique, spanning from negative through neutral to positive, with a pronounced peak in neutral sentiments. Motlanthe enjoys overwhelmingly positive feedback, with minimal divergences towards neutrality or negativity. In Zuma's case, a dominant concentration of neutral sentiments emerges, bracketed by almost equal measures of positive and negative sentiments. Ramaphosa's sentiment distribution is inclined towards positivity, but it doesn't lack a substantial count of neutral mentions and a minor portion of negative sentiments. 


```{python}
#| echo: false
#| fig-cap: "Figure X: RoBERTa 2 Distribution of Sentiment Scores for each President"
pastel_colors = ['#FFB3BA', '#FFDFBA', '#FFFFBA', '#BAFFC9', '#BAE1FF', '#D9BAFF']

def plot_histogram(president, color, ax):
    """Plot histogram of sentiment scores for a given president on a given axes."""
    president_df = HFM2[HFM2['Presidents'] == president]
    ax.hist(president_df['Sentiment_Score'], bins=30, color=color, edgecolor='white')
    ax.set_title(f'{president}')
    ax.set_xlabel('Sentiment Score')
    ax.set_ylabel('Frequency')
    ax.grid(axis='y', linestyle='--', linewidth=0.5)

# Creating a 2x3 grid plot for histograms of all presidents
fig, axes = plt.subplots(2, 3)

for president, color, ax in zip(adjusted_presidents_order, pastel_colors, axes.ravel()):
    plot_histogram(president, color, ax)

# Adjust layout
plt.tight_layout()
plt.subplots_adjust(top=0.90)
plt.show()
```



```{python}
#| echo: false
#| eval: false
a2tokens = pd.read_csv("finalTokens.csv")
tokens = [text.split() for text in a2tokens["Tokens"]]

# Create a dictionary and corpus
dct = corpora.Dictionary(tokens)
corpus = [dct.doc2bow(t) for t in tokens]

# Train the LDA models
m_lda_3 = LdaModel(corpus=corpus, num_topics=3, id2word=dct, passes=20)
m_lda_4 = LdaModel(corpus=corpus, num_topics=4, id2word=dct, passes=20)
m_lda_5 = LdaModel(corpus=corpus, num_topics=5, id2word=dct, passes=20)


# Print the topics and associated words
topics = m_lda.print_topics(num_words=10)
for topic in topics:
    print(topic)

# Prepare the visualization
vis3 = gensimvis.prepare(m_lda_3, corpus, dct)
vis4 = gensimvis.prepare(m_lda_4, corpus, dct)
vis5 = gensimvis.prepare(m_lda_5, corpus, dct)

# Save model and visualisation objects
# pyLDAvis.save_html(vis3, "lda_3topic_vis.html")
# m_lda_3.save("m_lda_3")
# pyLDAvis.save_html(vis4, "lda_4topic_vis.html")
# m_lda_4.save("m_lda_4")
# pyLDAvis.save_html(vis5, "lda_5topic_vis.html")
# m_lda_5.save("m_lda")

```


```{python}
#| echo: false
#| eval: false

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from gensim.models import LdaModel, LsiModel
from gensim import corpora
import pyLDAvis.gensim_models as gensimvis
import pyLDAvis

a2tokens = pd.read_csv("dsfi_assignment2/finalTokens.csv")
tokens = [text.split() for text in a2tokens["Tokens"]]

# Create a dictionary and corpus
dct = corpora.Dictionary(tokens)
corpus = [dct.doc2bow(t) for t in tokens]

## 4 topics
m_pLSA_4 = LsiModel(corpus=corpus, num_topics=4, id2word=dct)
m_pLSA_4.save("m_pLSA_4")
## 6 topics
m_pLSA_6 = LsiModel(corpus=corpus, num_topics=6, id2word=dct)
m_pLSA_6.save("m_pLSA_6")
## 9 topics
m_pLSA_9 = LsiModel(corpus=corpus, num_topics=9, id2word=dct)
m_pLSA_9.save("m_pLSA_9")
```


```{python}
#| echo: false
m_lda_3 = LdaModel.load("topic_models/m_lda_3")
m_lda_4 = LdaModel.load("topic_models/m_lda_4")
m_lda_5 = LdaModel.load("topic_models/m_lda")


def extract_topics(lda_model, m):
    df=pd.DataFrame({})
    topics = lda_model.print_topics(num_words=10)
    for i, topic in enumerate(topics):
        heading = i+1
        content = topic[1]
        items = content.split(' + ')
        tmp_df = pd.DataFrame({f'M{m} Topic {heading}': [item.strip().replace('"', '').replace('*', ' | ') for item in items]})
        df = pd.concat([df,tmp_df],axis=1)
    return df

topics_df = pd.concat([extract_topics(m_lda_3, 3),extract_topics(m_lda_4, 4),extract_topics(m_lda_5, 5)], axis=1)

```


```{python}
#| echo: false
#| fig-cap: "Figure X: Topic Weights and Terms Table"
data_display = []
lda_df = pd.read_csv("lda_all_topics_df.csv")
for i in range(lda_df.shape[0]):
    row = []
    for j in range(lda_df.shape[1]):
        row.append(lda_df.iloc[i, j])
    data_display.append(row)

# Plotting the table with bold headers
fig, ax = plt.subplots(figsize=(20, 10))
ax.axis('off')
ax.axis('tight')

table = ax.table(cellText=data_display, colLabels=lda_df.columns, cellLoc='center', loc='center')
table.auto_set_font_size(False)
table.set_fontsize(10)
table.auto_set_column_width(col=list(range(len(lda_df.columns))))
table.scale(1.5, 1.5)

# Bolding the headers
table.auto_set_font_size(False)
for (i, j), cell in table.get_celld().items():
    if i == 0:
        cell.set_text_props(fontweight='bold', color='w')
        cell.set_facecolor('#40466e')  # setting a dark background for contrast
plt.show()
```

```{python}
#| echo: false
#| eval: true
#| include: false


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
from sklearn.preprocessing import StandardScaler
from afinn import Afinn
 
#instantiate afinn
afn = Afinn()
data = pd.read_csv("finalSentences2.csv")

# compute scores (polarity) and labels
scores = [afn.score(sentence) for sentence in data["Sentences"]]
sentiment = ['positive' if score > 0
						else 'negative' if score < 0
							else 'neutral'
								for score in scores]
	
# dataframe creation
afn_df = pd.DataFrame()
afn_df['Presidents'] = data['Presidents']
afn_df['Sentences'] = data['Sentences']
afn_df['scores'] = scores
afn_df['sentiments'] = sentiment

# scaler = StandardScaler()
# scaled_data = scaler.fit_transform(afn_df['scores'].values.reshape(-1,1))
# afn_df['scores'] = scaled_data.squeeze()

presidents_order = ['Mandela', 'deKlerk', 'Mbeki', ' Motlanthe', 'Zuma', 'Ramaphosa']
mean_scores_per_president = afn_df.groupby('Presidents')['scores'].mean()
adjusted_presidents_order = ['deKlerk'] + [president for president in presidents_order if president != 'deKlerk']
mean_scores_reordered = mean_scores_per_president.reindex(adjusted_presidents_order)

# save object
# mean_scores_reordered.to_csv('wes_appendix/mean_scores_reordered.csv')
```

The mean sentiment scores per president show President Mbeki exhibiting the highest mean sentiment score at approximately 1.65, suggesting a generally positive sentiment in his speeches. President Motlanthe followed closely with a mean sentiment score of approximately 1.44, indicating a similar trend of positively oriented speeches. In contrast, President de Klerk presented the lowest mean sentiment score, around 0.67, while Presidents Ramaphosa and Zuma demonstrated mean sentiment scores around 0.95 and 0.92, respectively.


```{python}
#| echo: False
mean_scores_reordered = pd.read_csv('wes_appendix/mean_scores_reordered.csv')
# Plotting the reordered mean sentiment scores
plt.figure()
#mean_scores_reordered.plot(kind='bar', color='skyblue')
plt.bar(mean_scores_reordered['Presidents'], mean_scores_reordered['scores'], color='skyblue')

plt.title('Mean Sentiment Scores per President')

plt.title("Mean Sentiment Scores per President", fontsize=20)
plt.xlabel('President', fontsize=20)
plt.ylabel('Mean Sentiment Score', fontsize=20)
plt.xticks(rotation=45, fontsize=16)
plt.yticks(fontsize=16)  # Set the font size for y-axis tick labels
plt.tight_layout()
plt.show()
```

```{python}
#| echo: false
#| include: false
colors = {'negative': '#FF9999', 'neutral': '#99CCFF', 'positive': '#99FF99'}
sentiment_counts = afn_df.groupby('Presidents')['sentiments'].value_counts(normalize=True).unstack().fillna(0)
```


Figure X below shows that deKlerk is once again seen to possess less positive sentiments in his speeches than most of the other presidents, apart from Zuma, who has a very similar amount of positivity. Motlanthe and Mbeki are seen to have the greatest proportion of positive sentiments, while Zuma is seen to have the largest amount of neutral sentiments compared to the other presidents. As well as having the smallest proportion of positivity, deKlerk also has a large proportion of his sentences carrying negative sentiments.

```{python}
#| echo: false
# save object
# sentiment_counts.reindex(adjusted_presidents_order).to_csv('wes_appendix/sentiment_counts.csv')
sentiment_counts = pd.read_csv("wes_appendix/sentiment_counts.csv")
sentiment_counts.plot(kind='bar', stacked=True, color=[colors[col] for col in sentiment_counts.columns if col != 'Presidents'])
plt.title('Sentiment Distribution per President', fontsize=20)
plt.ylabel('Percentage', fontsize=20)
plt.xlabel('President', fontsize=20)
plt.legend(title='Sentiment', fontsize=20, title_fontsize=20)
plt.tight_layout()
plt.xticks(rotation=45, fontsize=16)
plt.yticks(fontsize=16) 
plt.show()
```


Figure Ax in the appendix shows the sentiments of each president over time. However, once again the extreme granularity of the plots makes it difficult to extract any useful information. Noticeably however, deKlerk's strong negative sentiments are apparent from such a broad scoped view.

```{python}
#| eval: true
#| include: false

from matplotlib.colors import LinearSegmentedColormap
from matplotlib import cm
from matplotlib import cm

def plot_for_president_gradient(president, df):
    # Filter dataframe for the selected president
    president_df = df[df['Presidents'] == president]
    
    # Sorting data by order (using the 'Unnamed: 0' column as the order)
    president_df = president_df.sort_values(by='Unnamed: 0')
    
    # Normalize the scores to [0,1] for colormap
    norm = plt.Normalize(-1, 1)
    
    # Custom colormap: Red -> Gray -> Blue
    custom_cmap = LinearSegmentedColormap.from_list("custom", ["red", "gray", "blue"])
    
    # Plotting with a black background and custom colormap
    fig, ax = plt.subplots()
    bars = ax.bar(np.arange(len(president_df)), president_df['Sentiment_Score'], 
                  color=custom_cmap(norm(president_df['Sentiment_Score'])), width=1.0)
    
    ax.set_title(f'Sentiment Score over time for President {president}')
    ax.set_xlabel('Order of Sentences')
    ax.set_ylabel('Sentiment Intensity')
    ax.axhline(0, color='white',linewidth=0.5)
    ax.grid(axis='y', color='white', linestyle='--', linewidth=0.5)
    ax.set_facecolor('black')
    fig.colorbar(cm.ScalarMappable(norm=norm, cmap=custom_cmap), ax=ax, label='Sentiment Score')
    
    plt.show()


presidents_list = afn_df['Presidents'].unique()
def plot_in_grid(president, ax):
    """Plot sentiment scores for a given president on a given axes."""
    president_df = afn_df[afn_df['Presidents'] == president]
    #president_df = president_df.sort_values(by='Unnamed: 0')
    
    # Normalize the scores for colormap
    norm = plt.Normalize(-1, 1)
    custom_cmap = LinearSegmentedColormap.from_list("custom", ["red", "gray", "blue"])

    bars = ax.bar(np.arange(len(president_df)), president_df['scores'], 
                  color=custom_cmap(norm(president_df['scores'])), width=1.0)
    ax.set_title(f'{president}', fontsize=20)
    ax.axhline(0, color='white', linewidth=0.5)
    ax.grid(axis='y', color='white', linestyle='--', linewidth=0.5)
    ax.set_facecolor('black')

# Creating a 2x3 grid plot for all presidents
fig, axes = plt.subplots(2, 3)
fig.suptitle('Sentiment Scores over time for each President', fontsize=20)

for president, ax in zip(adjusted_presidents_order, axes.ravel()):
    plot_in_grid(president, ax)

# Adjust layout
plt.tight_layout()
plt.subplots_adjust(top=0.90)

for ax in axes.ravel():
    ax.tick_params(axis='x', labelrotation=45, labelsize=16)
    ax.tick_params(axis='y', labelsize=16)

# Set x and y labels fontsize
for ax in axes[1, :]:
    ax.set_xlabel('Sentences', fontsize=20)
for ax in axes[:, 0]:
    ax.set_ylabel('Scores', fontsize=20)

plt.show()
```


The histograms below show the sentiment score distribution for the presidents. All histograms appear to be slightly skewed to the left, indicating a high frequency of positive sentiment. Mandela appears to have the most evenly spread sentiment distribution, with the fewest number of protruding bars, while de Klerk mainly has a uniform sentiment distribution, with a notable deviation from that occuring in the neutral sentiment territory. Ramaphosa's, Mbeki's and Zuma's sentiment distributions are both centered on the positive side of zero, indicating a generally positive sentiment, while Motlanthe's most common sentiment is actually slightly negative, however that is offset by the high frequency of positive sentiments.

```{python}
#| echo: false
#| eval: true

pastel_colors = ['#FFB3BA', '#FFDFBA', '#FFFFBA', '#BAFFC9', '#BAE1FF', '#D9BAFF']

def plot_histogram(president, color, ax):
    """Plot histogram of sentiment scores for a given president on a given axes."""
    president_df = afn_df[afn_df['Presidents'] == president]
    
    x_range = max(president_df['scores']) - min(president_df['scores'])
    half_x_range = x_range / 2
    
    # Set the x-axis limits to center the histogram around 0
    ax.set_xlim(-10, 10)

    ax.hist(president_df['scores'], bins=30, color=color, edgecolor='white')
    ax.set_title(f'{president}', fontsize=20)
    ax.set_xlabel('Sentiment Score', fontsize=20)
    ax.set_ylabel('Frequency', fontsize=20)
    ax.tick_params(axis='x', labelsize=16)
    ax.tick_params(axis='y', labelsize=16)
    ax.grid(axis='y', linestyle='--', linewidth=0.5)

# Creating a 2x3 grid plot for histograms of all presidents
fig, axes = plt.subplots(2, 3)
fig.suptitle('Distribution of Sentiment Scores for each President', fontsize=20)

for president, color, ax in zip(adjusted_presidents_order, pastel_colors, axes.ravel()):
    plot_histogram(president, color, ax)

# Adjust layout
plt.tight_layout()
plt.subplots_adjust(top=0.90)
plt.show()

```



### NRC

```{python}
#| echo: false
#| eval: true
#| include: false
import pandas as pd
from nrclex import NRCLex

# Function to find the top emotions for a text
def find_top_emotions(text):
    emotion = NRCLex(text)
    return emotion.top_emotions

# Apply the function to each row in the DataFrame
data['Top_Emotions'] = data['Sentences'].apply(find_top_emotions)

unique_emotion_columns = ['fear', 'anger', 'anticipation','anticip', 'trust', 'surprise', 'positive', 'negative', 'sadness', 'disgust', 'joy']
presidents = data['Presidents'].unique()

president_dataframes = {president: pd.DataFrame(0, columns=unique_emotion_columns, index=[0]) for president in presidents}

for index, row in data.iterrows():
    president = row['Presidents']
    emotions = dict(row['Top_Emotions'])
    #president_df = president_dataframes[president]
    
    # Iterate through unique_emotion_columns
    for emotion_column in emotions.keys():
        if emotion_column in emotions:
            value = emotions[emotion_column]
            president_dataframes[president][emotion_column] += value

president_dataframes['Mandela']

for pres in presidents:
    president_dataframes[pres] = president_dataframes[pres].div(president_dataframes[pres].sum(axis=1), axis=0)

for president, df in president_dataframes.items():
    if 'anticipation' in df.columns and 'anticip' in df.columns:
        df['anticipation'] += df['anticip']  # Add 'anticip' to 'anticipation'
        df.drop(columns=['anticip'], inplace=True)  # Remove 'anticip' column

pastel_colors = ['#FFB3BA', '#FFDFBA', '#FFFFBA', '#BAFFC9', '#BAE1FF', '#D9BAFF']
fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle('Distribution of Sentiment Scores for each President', fontsize=20)

order = ['deKlerk','Mandela', 'Mbeki', ' Motlanthe', 'Zuma', 'Ramaphosa']

for president, ax, colour in zip(order, axes.ravel(), pastel_colors):
    data = president_dataframes[president]
    x = list(data.keys())
    x.remove('positive')
    x.remove('negative')
    y = data[x].values.squeeze()
    ax.set_ylim(0, 0.25)
    ax.bar(x, y, color=colour)
    ax.set_title(president, fontsize=20)
    # ax.set_xlabel('Sentiment Category', fontsize=16)
    ax.set_ylabel('Sentiment Score', fontsize=16)
    ax.tick_params(axis='x', labelrotation=45, labelsize=16)
    ax.tick_params(axis='y', labelsize=16)

# Adjust layout
plt.tight_layout()
plt.subplots_adjust(top=0.90)
plt.show()
```

Using the NRC emotion lexicon we see that all presidents have their most common sentiment being positive, while the particular emotions in there sentences differ. A common emotion amongst all presidents is trust. Anticipation is a frequently evoked emotion from the presidents, besides for deKlerk. Other relatively common emotions include fear and joy.





## Latent Dirichlet Allocation

The ALL models were trained on the corpus of all thirty-six speeches, iteratively decreasing the number of topics from five until three. At five topics, two of the topics are almost overlaid - indicating that they are closely linked and probably contain a single topic. At four topics, one of the topics sits almost on the origin of the latent variables. This suggests that this 'topic' does not have differentiating features and likely consists of neutral words, for example it contains 'new', 'also', and a set of numbers, 'one', 'two', 'million'. The third model, with three topics, has three clearly differentiated topics sitting at the extremes of the latent variables axes. Three-topics models were then trained for each of the presidents, using only their respective speeches as the corpus. We gave the top ten words from each topic for each presidents' model and for the three-topic ALL model to ChatGPT to see if it could discern the nature of the topics identified by the LDA models. ChatGPT does a good job of drawing topic titles from the model output, but the further descriptions are hit and miss. The output from ChatGPT is as follows:  

LDA-Ramaphosa:

+ Topic 1: People and societal needs - this topic includes words related to the needs of the people and society. This could be associated with President Ramaphosa's focus on addressing the needs of the South African population, which could include policies related to social welfare and community development. 
    + Examples: "people," "need," "african".
+ Topic 2: Economic development and business - President Ramaphosa is known for promoting economic development and business growth in South Africa. This topic contains words related to business and economic sectors. 
    + Examples: "business," "government," "economic".
+ Topic 3: Time and work commitment - this topic contains words related to time and work commitment, possibly reflecting President Ramaphosa's commitment to his role and responsibilities as a leader. 
    + Examples: "year," "work," "must".

LDA-Zuma:

+ Topic 1: South Africa and government - this topic includes words related to South Africa and government. President Zuma's tenure was marked by various political and governmental issues, making this a prominent topic.
    + Examples: "south," "government," "africa"
+ Topic 2: Economic sectors and development - President Zuma's administration likely involved policies and discussions related to economic sectors and development, as indicated by the words in this topic.
    + Examples: "sector," "new," "economic"
+ Topic 3: Time and population - this topic may be associated with President Zuma's time in office and concerns related to the South African population.
    + Examples: "year," "country," "million"

LDA-Mandela:

+ Topic 1: Public affairs and the country - this topic encompasses words associated with public affairs and the country. Given Nelson Mandela's role as South Africa's first post-apartheid president, it's likely that topics related to the nation were significant.
    + Examples: "public," "country," "african"
+ Topic 2: Government work and public service - President Mandela's government focused on public service and the work required to build a new South Africa.
    + Examples: "government," "work," "service"
+ Topic 3: Time and commitment - Words related to time and commitment reflect Mandela's dedication to the country and his work.
    + Example: "year," "must," "national"

LDA-deKlerk:

+ Topic 1: Political alliance and elections - this topic includes words related to political alliances and elections. President de Klerk played a crucial role in the transition from apartheid to democracy.
    + Examples: "alliance," "election," "african"
+ Topic 2: Constitution and political parties - given his role in the negotiation of South Africa's new constitution, this topic reflects words related to the constitution and political parties.
    + Examples: "constitution," "party," "power"
+ Topic 3: South African provinces and constitutional concerns - the words in this topic may relate to the various provinces in South Africa and constitutional concerns that were addressed during his leadership.
    + Examples: "south," "province," "constitutional"

LDA-Mbeki:

+ Topic 1: Time and government programs - this topic could be associated with President Mbeki's focus on time-bound government programs and initiatives.
    + Examples: "year," "programme," "government"
+ Topic 2: National issues and the country - this topic encompasses words related to national issues and the country, reflecting his leadership during a period of significant national importance.
    + Examples: "country," "national," "work"
+ Topic 3: Economic sectors and government efforts - President Mbeki's administration focused on economic sectors and government efforts, as indicated by the words in this topic.
    + Examples: "sector," "effort," "government"

LDA-Motlanthe:

+ Topic 1 - South Africa and African development - this topic includes words related to South Africa and African development, reflecting a focus on regional and national development.
    + Examples: "south," "african," "development"
+ Topic 2: Government work and public sector - this topic likely represents the emphasis on government work and the public sector during President Motlanthe's leadership.
    + Examples: "government," "sector," "regard"
+ Topic 3: Economic development and work - words related to economic development and work suggest a focus on economic policies and employment during his tenure.
    + Examples: "economic," "work," "growth"

LDA-All:

+ Topic 1: South Africa and African development - this topic emphasizes South Africa and its development, which is a broad, overarching theme applicable to all six Presidents.
    + Examples: "south," "africa," "new"
+ Topic 2: People, work, and service - this topic encompasses words related to the people, their work, and the services provided, reflecting the importance of public service and commitment.
    + Examples: "people," "work," "service"
+ Topic 3 - Time and government - the words in this topic are related to time, government, and national affairs, indicating a focus on governance and the passage of time across all Presidential terms.
    + Examples: "year," "african," "government"

### Probablistic Latent Semantic Analysis

The weights produced for each word in the topics of the pLSA models are not very evenly distributed. This suggests that there may have be numerical difficulties in the computation during model training. pLSA models are very sensitive to data sparsity, the document-term matrix has only around a third of its cells populated. The model struggles to capture meaningful relationships through its dimensionality reduction techniques in the sparse data.


```{python}

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from gensim.models import LdaModel, LsiModel
from gensim import corpora


m_pLSA_4 = LsiModel.load("topic_models/m_pLSA_4")

num_words=20

topics = m_pLSA_4.print_topics(num_topics=4, num_words=num_words)
df4=pd.DataFrame({})
for topic in topics:
    content = topic[1]
    words=[]
    scores=[]
    scorewords = content.split(' + ')
    for item in scorewords:
        spl=item.split('*')
        scores.append(spl[0])
        words.append(spl[1].replace('"',''))
    topic_df=pd.DataFrame({f'T{topic[0]+1} Words': words, f'T{topic[0]+1} Scores': scores})
    df4 = pd.concat([df4, topic_df], axis=1)


# Create a 2x2 grid of subplots
fig, axs = plt.subplots(2, 2)
for i in [0,1]:
    for j in [0,1]:
        t=2*i+j+1
        axs[i, j].barh(df4[f'T{t} Words'], df4[f'T{t} Scores'])
        axs[i, j].set_xlabel('Words')
        axs[i, j].set_ylabel('Weight')
        axs[i, j].set_title(f'M4: Topic {t}')
        axs[i, j].tick_params(axis='x', rotation=90, labelsize=10)
        axs[i, j].tick_params(axis='y', rotation=0, labelsize=6)
plt.tight_layout()
plt.show()
```


# Discussion

The State of the Nation Address (SONA) gives an annual comprehensive overview of the nation’s progress, challenges, and future prospects. Through the application of Natural Language Processing (NLP), specifically sentiment analysis and topic modelling, this study has endeavoured to extract insights from these speeches to present a holistic, data-driven portrayal of the South African political landscape over three decades.

Using the RoBERTa, NRC, and Afinn models, the analysis provides a layered perspective of the country's political sentiment. RoBERTa's findings indicate that most presidents, from Mandela to Ramaphosa, conveyed an overall positive sentiment. The NRC model captured a spectrum of emotions, from trust and anticipation during Mandela's tenure to fear and surprise in Zuma's era. Afinn results largely corroborated with RoBERTa, strengthening the overall sentiment conclusions. Mandela's emphasis on societal unity and nation-building post-apartheid possibly fueled the positive sentiments. This trend continued with Mbeki, with an undercurrent of hope and trust. Zuma's era, intriguingly, maintained a high positive sentiment despite palpable emotions of fear and surprise, indicating a divergence between optimistic rhetoric and grounded realities. Ramaphosa's sentiments, while positive, were more subdued, reflecting challenges like the COVID-19 pandemic. In stark contrast, de Klerk’s tenure, as seen particularly in the NRC results, showed heightened emotions of sadness and fear, mirroring the transitional period around apartheid's end.

The LDA model effectively identified core themes across the terms. Mandela emphasized nation-building and unity. De Klerk, in contrast, focused on political alliances, reforms, and apartheid's complexities. Mbeki's speeches indicated shifts towards economic sectors and development. Motlanthe highlighted South Africa's broader African context, and Zuma balanced national and economic themes. However, Probabilistic Latent Semantic Analysis (pLSA) had challenges, emphasizing the importance of data quality and quantity for NLP projects.

# Limitations and Recommendations

While insightful, the study has limitations. Sentiment analysis can sometimes simplify complex rhetoric into basic sentiments, risking nuanced emotion loss. Relying on RoBERTa, while robust, could be complemented by other models for a rounded analysis. True class sentiment labels would allow rigorous model performance interrogation. Topic modelling, being interpretive, lacks quantifiable validation methods. Labelled data can facilitate model performance assessment.

# Conclusion

The NLP-based SONA speech analysis paints a multifaceted South African political journey narrative. As sentiments evolved and topics transitioned, they narrated a nation grappling with its past, shaping its present, and envisioning its future. With advancing NLP methodologies, such analyses will be pivotal in decoding global political and societal narratives.
